// Run against the local test harness only. No real account or message is used.
import assert from 'node:assert/strict'
const { chromium } = await import(process.env.THQ_PLAYWRIGHT_MODULE || 'playwright')
const browser = await chromium.launch({ headless: true, args: process.env.THQ_CHROMIUM_ARGS ? JSON.parse(process.env.THQ_CHROMIUM_ARGS) : [], ...(process.env.THQ_CHROMIUM_PATH ? { executablePath: process.env.THQ_CHROMIUM_PATH } : {}) })
try {
    const page = await browser.newPage({ viewport: { width: 1280, height: 900 } })
    const errors = []
    page.on('pageerror', (error) => errors.push(error.message))
    await page.goto(`${process.env.THQ_TEST_BASE_URL || 'http://127.0.0.1:5173'}/tests/whatsapp/ui-harness.html`)
    await page.getByRole('button', { name: 'Reconnect with Meta' }).waitFor()
    await page.locator('textarea').fill('Training Sunday\nPlease confirm attendance.')
    const share = page.getByRole('link', { name: 'Share to WhatsApp' })
    assert.equal(await share.getAttribute('href'), 'https://wa.me/?text=Training%20Sunday%0APlease%20confirm%20attendance.')
    assert.equal(await page.evaluate(() => window.lastSend), undefined, 'manual sharing must not create a delivery')
    await page.getByRole('button', { name: 'Review direct message' }).click()
    await page.getByRole('button', { name: 'WhatsApp', exact: false }).click()
    const template = page.getByLabel('WhatsApp service template')
    await template.selectOption('match_update|en_GB')
    await page.getByLabel('body field 1').fill('Sunday')
    await page.getByLabel('body field 2').fill('11am')
    assert.equal(await page.getByRole('button', { name: 'Send message', exact: true }).isDisabled(), true)
    await page.getByLabel('I confirm these recipients').check()
    await page.getByText('Match on Sunday at 11am.', { exact: true }).waitFor()
    await page.getByRole('button', { name: 'Send message', exact: true }).click()
    await page.waitForFunction(() => Boolean(window.lastSend))
    const sent = await page.evaluate(() => window.lastSend)
    assert.deepEqual(sent.channels, ['whatsapp'])
    assert.equal(sent.whatsappConsentConfirmed, true)
    assert.deepEqual(sent.whatsappTemplate, { name: 'match_update', language: 'en_GB', parameters: { 'body:1': 'Sunday', 'body:2': '11am' } })
    await page.getByRole('button', { name: 'Reconnect with Meta' }).click()
    await page.waitForFunction(() => Boolean(window.lastConnection))
    assert.equal((await page.evaluate(() => window.lastSignup)).extras.featureType, 'whatsapp_business_app_onboarding')
    await page.getByLabel('Account type').selectOption('platform')
    await page.getByRole('button', { name: 'Reconnect with Meta' }).click()
    assert.equal((await page.evaluate(() => window.lastSignup)).extras.featureType, undefined)
    await page.getByRole('button', { name: 'Disconnect', exact: true }).click()
    await page.getByRole('button', { name: 'Confirm disconnect' }).click()
    await page.getByRole('button', { name: 'Connect with Meta', exact: true }).waitFor()
    await page.setViewportSize({ width: 390, height: 844 })
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth), true, 'mobile page must not overflow')
    if (process.env.THQ_TEST_SCREENSHOT) await page.screenshot({ path: process.env.THQ_TEST_SCREENSHOT, fullPage: true })
    assert.deepEqual(errors, [])
    console.log('PASS: manual share text, no fake delivery, approved-template review, consent gate, exact send payload, both signup paths, disconnect and mobile layout.')
} finally { await browser.close() }
